# Generated by Django 3.2.6 on 2021-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundimage', models.ImageField(upload_to='posts/')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
    ]
