# Generated by Django 3.2.6 on 2021-08-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
