# Generated by Django 3.2.6 on 2021-08-18 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('datefrom', models.DateField(default=django.utils.timezone.now)),
                ('dateto', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
