# Generated by Django 3.2.6 on 2021-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twitter', models.URLField(default='')),
                ('Facebook', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('Pinsterst', models.URLField(default='')),
            ],
        ),
    ]
